### PR TITLE
Add initial version

### LINKED ISSUE #1: AWS Parameter Store Component
Create a parameter store that allows synchronizing multiple SSM parameters and Secrets Manager secrets to AWS.

The declarative syntax is going to be something like this

```yaml
myParameterStore:
  component: '@serverless/aws-parameter-store'
  inputs:
    parameters:
      - name: /my/parameter/name
        value: '000000'
        type: AWS/SSM/SecureString # something like this
      - name: parameter-name
        value: just-a-string
        type: AWS/SSM/String  # something like this
      - name: pg_password
        value: 'secret'
        type: AWS/SecretsManager  # something like this
        # + whatever parameters are needed, KMS id etc.
```

The component will output the ARN and version (SSM) for each of the parameters.

I'll refine the specification while implementing and open the PR later.

### PR DESCRIPTION
**Pull request by laardee**
This PR will add an initial version of the AWS parameter store component.

## serverless.yml

Declarative syntax for parameter store component with SSM string, SSM, and a SecretsManager entry.

```yaml
name: my-service
stage: dev

myParameters:
  component: '@serverless/aws-parameter-store'
  inputs:
    parameters:
      - name: /my/credentials/username
        value: 'bob'
        type: SSM/String
      - name: /my/credentials/password
        value: 'abc123xyz456'
        type: SSM/SecureString
      - name: my_credentials
        value: '{"username":"bob", "password":"abc123xyz456"}'
        type: SecretsManager/SecretString
```

Same with optional attributes

```yaml
name: my-service
stage: dev

myParameters:
  component: '@serverless/aws-parameter-store'
  inputs:
    parameters:
      - name: /my/credentials/username
        value: 'bob'
        type: SSM/String
        description: my username # optional
      - name: /my/credentials/password
        value: 'abc123xyz456'
        type: SSM/SecureString
        kmsKey: arn:aws:kms:us-east-1:123456789012:key/a67b9750-235a-432b-99e4-6c59516d4f07 # optional
        description: my password # optional
        tier: Standard # optional
      - name: my_credentials
        value: '{"username":"bob", "password":"abc123xyz456"}'
        type: SecretsManager/SecretString
        kmsKey: arn:aws:kms:us-east-1:123456789012:key/a67b9750-235a-432b-99e4-6c59516d4f07 # optional
        description: my credentials # optional
        resourcePolicy: # optional
          Version: '2012-10-17'
          Statement:
          - Effect: Allow
            Principal:
              AWS: arn:aws:iam::123456789012:root
            Action: secretsmanager:GetSecretValue
            Resource: "*"
```

Missing from the initial version
- SSM policies, which are used to trigger e.g. change events
- SecretsManager key rotation feature

## outputs
I noticed that it is not possible to refer component output if it contains slashes, so the output keys are sanitized names of the variables. e.g. `/my/credentials/password` -> `my_credentials_password`.
output

```shell
 my_credentials_password:
    name:  '/my/credentials/password'
    arn:  'arn:aws:ssm:us-east-1:123456789012:parameter/my/credentials/password'
    version:  1
```

Example how to reference in another component
```yaml
name: my-service
stage: dev

myParameters:
  component: '@serverless/aws-parameter-store'
  inputs:
    parameters:
      - name: /my/credentials/password # -> my_credentials_password
        value: 'abc123xyz456'
        type: SSM/SecureString
  myFunction:
    component: '@serverless/aws-lambda'
    inputs:
      env:
        PASSWORD_ARN: ${comp:myParameterStore.my_credentials_password.arn} # the arn is used here
```
In this case the Lambda function would use the arn to fetch the value from SSM on runtime.

closes #1

### CODE REVIEW

**Comment by laardee** [comment]
@eahefnawy I think this is ready for the first round

**Comment by eahefnawy** [comment]
Thanks @laardee ... the PR looks good. I've noticed that you still haven't added any `cli` logs/outputs. That's good because we just pushed component v0.2.0 which is breaking the following ways:

- `this.cli` object is now replaced to `this.ui`. We're investigating adding an electron app and we wanna make component agnostic to the kind of "UI" that is passed in.
- `this.cli.outputs` has been removed and replaced with `this.ui.output` (singular). Dumping the entire outputs object didn't provide a great UI experience, so we're giving component authors the ability to format each output according to their needs.
- we've moved the core utils to its own `utils` object rather than at the top level. so you'll need to do `utils.sleep` instead of `sleep`. I don't see you using the utils here, so that shouldn't be an issue.

I've already updated all components. Would be great to update this one as well. Just use `@serverless/components@0.2.0`

Hope this helps! 🚀

**Review by eahefnawy — CHANGES_REQUESTED** [review]
Thanks @laardee ... the PR looks good. I've noticed that you still haven't added any `cli` logs/outputs. That's good because we just pushed component v0.2.0 which is breaking the following ways:

- `this.cli` object is now replaced to `this.ui`. We're investigating adding an electron app and we wanna make component agnostic to the kind of "UI" that is passed in.
- `this.cli.outputs` has been removed and replaced with `this.ui.output` (singular). Dumping the entire outputs object didn't provide a great UI experience, so we're giving component authors the ability to format each output according to their needs.
- we've moved the core utils to its own `utils` object rather than at the top level. so you'll need to do `utils.sleep` instead of `sleep`. I don't see you using the utils here, so that shouldn't be an issue.

I've already updated all components. Would be great to update this one as well. Just use `@serverless/components@0.2.0`

Hope this helps! 🚀

**Comment by laardee** [comment]
@eahefnawy thanks for the tips, I added some status messages and new output format. 

Now the output is something like this

```console
  my_credentials_password.name:    /my/credentials/password
  my_credentials_password.arn:     arn:aws:ssm:us-east-1:123456789012:parameter/my/credentials/password
  my_credentials_password.version: 1
  my_credentials_username.name:    /my/credentials/username
  my_credentials_username.arn:     arn:aws:ssm:us-east-1:123456789012:parameter/my/credentials/username
  my_credentials_username.version: 1
  my_credentials.name:    my_credentials
  my_credentials.arn:     arn:aws:secretsmanager:us-east-1:123456789012:secret:my_credentials-fxdLpu
  my_credentials.version: add085ab-3dd4-48e2-9232-11e521e1da57
 ```

but I would hope it to be like this

```console
  my_credentials_password:
    name:    /my/credentials/password
    arn:     arn:aws:ssm:us-east-1:123456789012:parameter/my/credentials/password
    version: 1
  my_credentials_username:
    name:    /my/credentials/username
    arn:     arn:aws:ssm:us-east-1:123456789012:parameter/my/credentials/username
    version: 1
  my_credentials:
    name:    my_credentials
    arn:     arn:aws:secretsmanager:us-east-1:123456789012:secret:my_credentials-fxdLpu
    version: add085ab-3dd4-48e2-9232-11e521e1da57
```

How do I manage to do that?

If I try to do it this way (the actual code is in a loop because the key names are dynamic, but the idea is the same)

```js
      this.ui.output('my_credentials_password', ' ')
      this.ui.output(`  name`, `   ${name}`)
      this.ui.output(`  arn`, `    ${arn}`)
      this.ui.output(`  version`, `${version}`)
      this.ui.output('my_credentials_username', ' ')
      this.ui.output(`  name`, `   ${name}`)
      this.ui.output(`  arn`, `    ${arn}`)
      this.ui.output(`  version`, `${version}`)
```

only the first set of `name`, `arn`, and `version` is displayed

```console
  my_credentials_password:  
    name:    /my/credentials/username
    arn:     arn:aws:ssm:us-east-1:123456789012:parameter/my/credentials/username
    version: 1
  my_credentials_username:  

2s › dev › test-function-service › done
```

I'm ok with the first one, but the second option would be readable.

**Review by eahefnawy — APPROVED** [review]
Thanks @laardee ... the first option for outputs is fine for now. But since you have a complex object, you could ditch the `.output` method and do everything with `.log` instead and control the formatting with line breaks and so on. I'm doing something similar with other components that has complex outputs, like the APIG component. I'm just listing the endpoints as a list using `.log`. I would only use `.output` if it's a simple key/value pair.

Overall, we're making a distinction between CLI outputs and the full outputs object that is returned programatically. For best UX, we don't think all outputs are display-worthy. It's up to the component author to decide which outputs to display.

I'm merging this for now. Thanks a lot for your hard work! And sorry for the constant breakage!

**Pull request merged**
